# Generated by Django 5.0.2 on 2024-02-21 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_card_id_card_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/main/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='card',
            name='pdf',
            field=models.FileField(default=' ', upload_to='static/main/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Pdf'),
            preserve_default=False,
        ),
    ]
