# Generated by Django 5.0.2 on 2024-02-21 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_image_card_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pdf',
            field=models.FileField(default=' ', upload_to='static/main/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Pdf'),
        ),
    ]
