# Generated by Django 5.0.2 on 2024-02-21 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_card_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pdf',
            field=models.FileField(default=' ', upload_to='pdfs', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Pdf'),
        ),
    ]
